baseurl = "http://chasex.github.io/"
languageCode = "en-us"
title = "Chasex's Blog"
# Enable comments by entering your Disqus shortname
disqusShortname = "chasex"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per site
paginate = 10
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you're
    author = "Chasex"
    bio = "Linux Programmer"
    location = "China"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."

    # Format dates with Go's time formating
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "/tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "/categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/chasex"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "chasex"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "wu.xibin.7"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = false
